name: Node Continuous Integration

on:
  pull_request:
    branches: [ master ]
    


jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v2
        with:
          # Token for the repository. Can be passed in using `{{ secrets.GITHUB_TOKEN }}`.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Official SonarQube Scan
        # You may pin to the exact commit or the version.
        # uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
        uses: SonarSource/sonarqube-scan-action@v1.1.0
      - run: npm ci
      - run: npm test

      - run: npm run build
      - name: 'Checkout Repository'
        uses: actions/checkout@v3


        

